name: Check Squash Conventional Commit

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-squash-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message
        uses: actions/github-script@v7
        with:
          script: |
            const prTitle = context.payload.pull_request.title;
            const prNumber = context.payload.pull_request.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;

            const regex = /^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-zA-Z0-9][a-zA-Z0-9 \-]*\))?!?: .{1,};

            if (!regex.test(prTitle)) {
              core.setFailed(
                `❌ Invalid squash commit message: "${prTitle}"\n` +
                `Format should be: "ABC-123: short description"`
              );
            } else {
              core.info(`✅ Commit message format looks good: "${prTitle}"`);
            }
